base_model = (;
    R = 70,
    w = 0,
    d = 0,
    Δ0 = 0.23,
    ξd = 70,
    a0 = 5,
    preα = 0,
    g = 0,
    α = 0,
    μ = 0,
    τΓ = 1,
    Vexponent = 2,
    Vmin = 0,
    Vmax = 0,
    ishollow = true,
)
models = Dict(
    "HCA" => (;
        base_model...,
        μ = 0.75,
        α = 85,
    ),
    "TCM_30" => (;
        base_model...,
        w = 30,
        τΓ = 26,
        μ = 10.4,
        α = 35,
        ishollow = false,
    ),
    "SCM" => (;
        base_model...,
        w = 70,
        d = 10,
        Vmin = -30,
        g = 10,
        τΓ = 40,
        μ = 2,
        preα = 46.66,
        ishollow = false,
    ),
    "TCM_20_island" => (;
        base_model...,
        w = 20,
        τΓ = 12,
        μ = 18.1,
        α = 50,
        ishollow = false,
    ),
    "TCM_20_gapped" => (;
        base_model...,
        w = 20,
        τΓ = 12,
        μ = 18.5,
        α = 50,
        ishollow = false,
    ),
)