base_wire = (;
    R = 70,
    w = 0,
    d = 5,
    Δ0 = 0.23,
    ξd = 70,
    a0 = 5,
    preα = 0,
    g = 0,
    α = 0,
    μ = 0,
    τΓ = 1,
    Vexponent = 2,
    Vmin = 0,
    Vmax = 0,
    ishollow = true,
)
wires = Dict(
    "HCA" => (;
        base_wire...,
        μ = 0.75,
        α = 85,
    ),
    "MHC_20" => (;
        base_wire...,
        w = 20,
        μ = 0.75,
        α = 85,
        L = 0,
    ),
    "MHC_20_ξ" => (;
        base_wire...,
        w = 20,
        μ = 0.75,
        α = 85,
        L = 0,
        ξd = 150,
    ),
    "MHC_20_60" => (;
        base_wire...,
        w = 20,
        μ = 0.75,
        α = 85,
        L = 0,
        R = 60,
    ),
    "SCM" => (;
        base_wire...,
        w = 70,
        d = 10,
        Vmin = -30,
        g = 10,
        τΓ = 40,
        μ = 2,
        preα = 46.66,
        ishollow = false,
    ),
    "TCM_20_triv" => (;
        base_wire...,
        w = 20,
        d = 10,
        τΓ = 10,
        μ = 18.7,
        α = 50,
        g = 10,
        ishollow = false,
    ),
    "TCM_20_island" => (;
        base_wire...,
        w = 20,
        d = 10,
        τΓ = 10,
        μ = 18.1,
        α = 50,
        g = 10,
        ishollow = false,
    ),
    "TCM_20_gapless" => (;
        base_wire...,
        w = 20,
        d = 10,
        τΓ = 10,
        μ = 18.5,
        α = 50,
        g = 10,
        ishollow = false,
    ),
    "TCM_40" => (;
        base_wire...,
        w = 40,
        d = 10,
        μ = 6.95,
        α = 20,
        τΓ = 48,
        g = 10,
        ishollow = false,
    ),
)
